In [1]:
import numpy as np

建立一維 ndarray

In [4]:
mat = np.array([1,2,3])
print(type(mat))
print(mat)

<class 'numpy.ndarray'>
[1 2 3]


建立二維 ndarray

In [1]:
mat2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(type(mat2))
print(mat2)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### ndarray 物件常用的屬性
<span style="color:orange">ndarray.shape</span> Tuple of array dimentions  //幾乘幾的陣列

<span style="color:orange">ndarray.ndim</span> Number of array dimensions //幾個維度

<span style="color:orange">ndarray.size</span> Number of elements in the array //矩陣中的元素有幾個

<span style="color:orange">ndarray.dtype</span> Data-type of the array's elements //64位元整數

<span style="color:orange">ndarray.T</span> Same as self.transpose(), except that self is returned if self.ndim<2  //轉換成3x2的矩陣

In [2]:
mat3 = np.array([[1,2,3],[4,5,6]])
print(mat3)
print('.shape:', mat3.shape)
print('.ndim:', mat3.ndim)
print('.size:', mat3.size)
print('.dtype:', mat3.dtype)
print('.dtype:', mat3.T)

[[1 2 3]
 [4 5 6]]
.shape: (2, 3)
.ndim: 2
.size: 6
.dtype: int64
.dtype: [[1 4]
 [2 5]
 [3 6]]


In [3]:
mat = np.arange(8)
print(mat)

[0 1 2 3 4 5 6 7]


In [4]:
mat = np.arange(3,8)
print(mat)

[3 4 5 6 7]


In [5]:
mat = np.arange(3,8,2)
print(mat)

[3 5 7]


### 創建一個預設矩陣：全零或全一矩陣
np.zeros((行數，列數))

In [3]:
mat = np.zeros((2,3))
print(mat)

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
mat = np.ones((2,4))
print(mat)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
