In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
A = np.random.randn(100)

In [3]:
A

array([ 0.83767133,  1.45959305,  0.37923307,  0.40664926, -1.78909598,
       -0.08735642,  1.89734475,  0.48184307, -0.16522041,  0.21208736,
       -0.97408432, -1.09500783,  1.58747837, -1.16962467,  0.94972314,
       -0.54991447, -0.69292109,  0.48645569,  2.34917845,  1.03020954,
        0.96184563,  0.79277854,  0.92683915, -0.32350793, -0.04644461,
        1.11940651, -0.58160254, -1.48827161,  1.04268629, -1.05786551,
        2.41195349, -0.09292983,  0.53894001, -1.22854098,  0.38159144,
        0.5299006 , -0.17188828,  0.31641973, -1.30698714, -0.19246622,
       -0.83889245,  1.19010533, -1.42879657, -0.49443301, -0.0874598 ,
       -1.32127845,  0.92228589,  0.31410347,  0.93459338, -0.03497005,
        1.14557125,  0.92499652,  0.83130778,  0.95238826,  0.31131649,
       -0.92911604,  0.85877996, -1.93590031, -1.38753654, -1.02269905,
       -2.18136828,  0.12941572, -0.77428108,  1.09781345,  0.0784092 ,
        0.09218864, -0.39691172,  0.10195628, -1.27751355,  0.53

In [4]:
A*10 + 50

array([58.37671332, 64.59593048, 53.79233075, 54.06649264, 32.10904017,
       49.1264358 , 68.97344746, 54.8184307 , 48.34779585, 52.1208736 ,
       40.2591568 , 39.04992172, 65.87478372, 38.30375327, 59.49723144,
       44.50085531, 43.07078912, 54.86455685, 73.49178452, 60.30209537,
       59.61845633, 57.92778542, 59.26839155, 46.76492066, 49.53555386,
       61.19406512, 44.18397459, 35.1172839 , 60.42686287, 39.42134495,
       74.11953487, 49.0707017 , 55.38940006, 37.7145902 , 53.81591443,
       55.29900601, 48.28111719, 53.16419727, 36.93012862, 48.07533776,
       41.6110755 , 61.90105326, 35.71203429, 45.05566993, 49.12540198,
       36.7872155 , 59.22285886, 53.14103472, 59.3459338 , 49.65029947,
       61.45571251, 59.24996523, 58.31307781, 59.52388257, 53.11316486,
       40.70883964, 58.58779958, 30.64099685, 36.12463459, 39.77300951,
       28.18631719, 51.29415717, 42.25718917, 60.9781345 , 50.78409199,
       50.92188639, 46.03088275, 51.01956284, 37.22486449, 55.37

In [5]:
A.shape

(100,)

In [7]:
A.shape = (5,20)

In [8]:
A

array([[ 0.83767133,  1.45959305,  0.37923307,  0.40664926, -1.78909598,
        -0.08735642,  1.89734475,  0.48184307, -0.16522041,  0.21208736,
        -0.97408432, -1.09500783,  1.58747837, -1.16962467,  0.94972314,
        -0.54991447, -0.69292109,  0.48645569,  2.34917845,  1.03020954],
       [ 0.96184563,  0.79277854,  0.92683915, -0.32350793, -0.04644461,
         1.11940651, -0.58160254, -1.48827161,  1.04268629, -1.05786551,
         2.41195349, -0.09292983,  0.53894001, -1.22854098,  0.38159144,
         0.5299006 , -0.17188828,  0.31641973, -1.30698714, -0.19246622],
       [-0.83889245,  1.19010533, -1.42879657, -0.49443301, -0.0874598 ,
        -1.32127845,  0.92228589,  0.31410347,  0.93459338, -0.03497005,
         1.14557125,  0.92499652,  0.83130778,  0.95238826,  0.31131649,
        -0.92911604,  0.85877996, -1.93590031, -1.38753654, -1.02269905],
       [-2.18136828,  0.12941572, -0.77428108,  1.09781345,  0.0784092 ,
         0.09218864, -0.39691172,  0.10195628, -

In [9]:
A.reshape(100,1)

array([[ 0.83767133],
       [ 1.45959305],
       [ 0.37923307],
       [ 0.40664926],
       [-1.78909598],
       [-0.08735642],
       [ 1.89734475],
       [ 0.48184307],
       [-0.16522041],
       [ 0.21208736],
       [-0.97408432],
       [-1.09500783],
       [ 1.58747837],
       [-1.16962467],
       [ 0.94972314],
       [-0.54991447],
       [-0.69292109],
       [ 0.48645569],
       [ 2.34917845],
       [ 1.03020954],
       [ 0.96184563],
       [ 0.79277854],
       [ 0.92683915],
       [-0.32350793],
       [-0.04644461],
       [ 1.11940651],
       [-0.58160254],
       [-1.48827161],
       [ 1.04268629],
       [-1.05786551],
       [ 2.41195349],
       [-0.09292983],
       [ 0.53894001],
       [-1.22854098],
       [ 0.38159144],
       [ 0.5299006 ],
       [-0.17188828],
       [ 0.31641973],
       [-1.30698714],
       [-0.19246622],
       [-0.83889245],
       [ 1.19010533],
       [-1.42879657],
       [-0.49443301],
       [-0.0874598 ],
       [-1

In [10]:
A

array([[ 0.83767133,  1.45959305,  0.37923307,  0.40664926, -1.78909598,
        -0.08735642,  1.89734475,  0.48184307, -0.16522041,  0.21208736,
        -0.97408432, -1.09500783,  1.58747837, -1.16962467,  0.94972314,
        -0.54991447, -0.69292109,  0.48645569,  2.34917845,  1.03020954],
       [ 0.96184563,  0.79277854,  0.92683915, -0.32350793, -0.04644461,
         1.11940651, -0.58160254, -1.48827161,  1.04268629, -1.05786551,
         2.41195349, -0.09292983,  0.53894001, -1.22854098,  0.38159144,
         0.5299006 , -0.17188828,  0.31641973, -1.30698714, -0.19246622],
       [-0.83889245,  1.19010533, -1.42879657, -0.49443301, -0.0874598 ,
        -1.32127845,  0.92228589,  0.31410347,  0.93459338, -0.03497005,
         1.14557125,  0.92499652,  0.83130778,  0.95238826,  0.31131649,
        -0.92911604,  0.85877996, -1.93590031, -1.38753654, -1.02269905],
       [-2.18136828,  0.12941572, -0.77428108,  1.09781345,  0.0784092 ,
         0.09218864, -0.39691172,  0.10195628, -

In [11]:
A = A.reshape(100,1)

In [12]:
A

array([[ 0.83767133],
       [ 1.45959305],
       [ 0.37923307],
       [ 0.40664926],
       [-1.78909598],
       [-0.08735642],
       [ 1.89734475],
       [ 0.48184307],
       [-0.16522041],
       [ 0.21208736],
       [-0.97408432],
       [-1.09500783],
       [ 1.58747837],
       [-1.16962467],
       [ 0.94972314],
       [-0.54991447],
       [-0.69292109],
       [ 0.48645569],
       [ 2.34917845],
       [ 1.03020954],
       [ 0.96184563],
       [ 0.79277854],
       [ 0.92683915],
       [-0.32350793],
       [-0.04644461],
       [ 1.11940651],
       [-0.58160254],
       [-1.48827161],
       [ 1.04268629],
       [-1.05786551],
       [ 2.41195349],
       [-0.09292983],
       [ 0.53894001],
       [-1.22854098],
       [ 0.38159144],
       [ 0.5299006 ],
       [-0.17188828],
       [ 0.31641973],
       [-1.30698714],
       [-0.19246622],
       [-0.83889245],
       [ 1.19010533],
       [-1.42879657],
       [-0.49443301],
       [-0.0874598 ],
       [-1